import type { Movie } from '@/types/movie'
import type { User } from '@/types/user'
import type { Rating } from '@/types/rating'
import type { Recommendation } from '@/types/recommendation'

export const mockUsers: User[] = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@reelmind.app',
    role: 'admin',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=admin',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'Jan Kowalski',
    email: 'user@reelmind.app',
    role: 'user',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=jan',
    createdAt: '2024-03-15T10:00:00Z',
  },
]

export const mockPasswords: Record<string, string> = {
  'admin@reelmind.app': 'admin123',
  'user@reelmind.app': 'user123',
}

export const mockMovies: Movie[] = [
  {
    id: 1,
    title: 'Inception',
    description:
      'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    genre: ['Sci-Fi', 'Action', 'Thriller'],
    year: 2010,
    rating: 8.8,
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    duration: 148,
    posterUrl: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    language: 'en',
    country: 'USA',
    trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
  },
  {
    id: 2,
    title: 'The Shawshank Redemption',
    description:
      'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    genre: ['Drama'],
    year: 1994,
    rating: 9.3,
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    duration: 142,
    posterUrl: 'https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    language: 'en',
    country: 'USA',
  },
  {
    id: 3,
    title: 'The Dark Knight',
    description:
      'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    genre: ['Action', 'Drama', 'Thriller'],
    year: 2008,
    rating: 9.0,
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    duration: 152,
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
    language: 'en',
    country: 'USA',
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
  },
  {
    id: 4,
    title: 'Pulp Fiction',
    description:
      'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    genre: ['Drama', 'Thriller'],
    year: 1994,
    rating: 8.9,
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    duration: 154,
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    language: 'en',
    country: 'USA',
  },
  {
    id: 5,
    title: 'Fight Club',
    description:
      'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.',
    genre: ['Drama', 'Thriller'],
    year: 1999,
    rating: 8.8,
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    duration: 139,
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg',
    language: 'en',
    country: 'USA',
  },
  {
    id: 6,
    title: 'The Matrix',
    description:
      'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genre: ['Sci-Fi', 'Action'],
    year: 1999,
    rating: 8.7,
    director: 'Lana Wachowski',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    duration: 136,
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/ncEsesgOJDNrTUED89hYbA117wo.jpg',
    language: 'en',
    country: 'USA',
    trailerUrl: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
  },
  {
    id: 7,
    title: 'Forrest Gump',
    description:
      'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
    genre: ['Drama', 'Romance'],
    year: 1994,
    rating: 8.8,
    director: 'Robert Zemeckis',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    duration: 142,
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg',
    language: 'en',
    country: 'USA',
  },
  {
    id: 8,
    title: 'The Truman Show',
    description:
      "An insurance salesman discovers his whole life is actually a reality TV show.",
    genre: ['Drama', 'Comedy', 'Sci-Fi'],
    year: 1998,
    rating: 8.2,
    director: 'Peter Weir',
    cast: ['Jim Carrey', 'Ed Harris', 'Laura Linney'],
    duration: 103,
    posterUrl: 'https://image.tmdb.org/t/p/w500/vuza0WqY239yBXOadKlGwJsZJFE.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/hdjl8tFuPtPDXXaHBPGDHlbfKTJ.jpg',
    language: 'en',
    country: 'USA',
  },
  {
    id: 9,
    title: 'Interstellar',
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genre: ['Sci-Fi', 'Drama'],
    year: 2014,
    rating: 8.7,
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    duration: 169,
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/pbrkL804c8yAv3zBZR4QPEafpAR.jpg',
    language: 'en',
    country: 'USA',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
  },
  {
    id: 10,
    title: 'Harry Potter and the Sorcerer\'s Stone',
    description:
      'An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.',
    genre: ['Fantasy', 'Drama'],
    year: 2001,
    rating: 7.6,
    director: 'Chris Columbus',
    cast: ['Daniel Radcliffe', 'Emma Watson', 'Rupert Grint'],
    duration: 152,
    posterUrl: 'https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/hziiv14OpD73u9gAak4XiTBgTzV.jpg',
    language: 'en',
    country: 'UK',
  },
  {
    id: 11,
    title: 'Goodfellas',
    description:
      'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
    genre: ['Drama', 'Thriller'],
    year: 1990,
    rating: 8.7,
    director: 'Martin Scorsese',
    cast: ['Ray Liotta', 'Robert De Niro', 'Joe Pesci'],
    duration: 145,
    posterUrl: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/sw7mordbZxgITU877yTpZCud90M.jpg',
    language: 'en',
    country: 'USA',
  },
  {
    id: 12,
    title: 'Spirited Away',
    description:
      'During her family\'s move to the suburbs, a sulky 10-year-old girl wanders into a world ruled by gods, witches, and spirits.',
    genre: ['Animation', 'Fantasy', 'Drama'],
    year: 2001,
    rating: 8.6,
    director: 'Hayao Miyazaki',
    cast: ['Daveigh Chase', 'Suzanne Pleshette', 'Miyu Irino'],
    duration: 125,
    posterUrl: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg',
    language: 'ja',
    country: 'Japan',
  },
]

export const mockRatings: Rating[] = [
  { id: 1, movieId: 1, userId: 2, value: 9, review: 'Mind-bending masterpiece!', createdAt: '2024-02-10T12:00:00Z' },
  { id: 2, movieId: 3, userId: 2, value: 10, review: 'Heath Ledger was incredible.', createdAt: '2024-02-15T09:30:00Z' },
  { id: 3, movieId: 6, userId: 2, value: 8, review: 'Still a classic.', createdAt: '2024-03-01T18:00:00Z' },
  { id: 4, movieId: 9, userId: 2, value: 9, review: 'Visually stunning and emotionally powerful.', createdAt: '2024-03-20T20:00:00Z' },
]

export const mockWatchlist: number[] = [2, 5, 7, 12]

export const mockRecommendations: Recommendation[] = [
  { movie: mockMovies[0]!, score: 0.97, reason: 'Based on your love of sci-fi thrillers' },
  { movie: mockMovies[2]!, score: 0.95, reason: 'You enjoy Christopher Nolan films' },
  { movie: mockMovies[8]!, score: 0.93, reason: 'Matches your interest in space exploration stories' },
  { movie: mockMovies[11]!, score: 0.91, reason: 'You enjoy fantasy and animated films' },
  { movie: mockMovies[10]!, score: 0.89, reason: 'Based on your high rating for crime dramas' },
  { movie: mockMovies[3]!, score: 0.87, reason: 'Quentin Tarantino matches your taste profile' },
]
